config/routes.rb
Rails.application.routes.draw do
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/edit'
  # get 'sections/delete'

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'

  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  # get 'test/index'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'


  # get ':controller(/:action(:/id))'
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in, except: %i[login attempt_login logout]

  def menu
    # display text & links
  end

  def login
    # login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are now logged in."
      redirect_to(admin_path)
    else
      flash.now[:notice] = "Invalid username/password combination."
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to(access_login_path)
  end


end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = "Admin Login" %>

<div class="container mx-auto max-w-md p-4">
  <h1 class="font-bold text-4xl mb-6">Admin Login</h1>
  
  <%= form_tag(access_attempt_login_path, method: :post, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do %>
    <div class="mb-4">
      <%= label_tag :username, "Username", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= text_field_tag :username, params[:username], class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="mb-6">
      <%= label_tag :password, "Password", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= password_field_tag :password, nil, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="flex items-center justify-between">
      <%= submit_tag 'Log In', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu" %>

<div class="container mx-auto p-4">
  <h1 class="font-bold text-4xl mb-4">Admin Menu</h1>
  <div class="mb-2">Logged in as:</div>
  <ul class="list-disc pl-5">
    <li class="mb-2"><%= link_to("Manage Subjects", subjects_path, class: "text-blue-500 hover:text-blue-700") %></li>
    <li class="mb-2"><%= link_to("Manage Pages", pages_path, class: "text-blue-500 hover:text-blue-700") %></li>
    <li class="mb-2"><%= link_to("Manage Sections", sections_path, class: "text-blue-500 hover:text-blue-700") %></li>
    <li class="mb-2"><%= link_to("Manage Admin Users", '#', class: "text-blue-500 hover:text-blue-700") %></li>
    <li class="mb-2"><%= link_to("Logout", access_logout_path, class: "text-red-500 hover:text-red-700") %></li>
  </ul>
</div>