config/routes.rb
Rails.application.routes.draw do
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/edit'
  # get 'sections/delete'

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'

  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  # get 'test/index'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'


  # get ':controller(/:action(:/id))'
end

app/models/subject.rb
class Subject < ApplicationRecord

  # has_one :page
  has_many :pages

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
  scope :search, ->(query) { where(['name LIKE ?', "%#{query}%"]) }

  validates :name, presence: true, length: { minimum: 3, maximum: 255 }

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
    @subject_count = Subject.count + 1
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = 'Subject created successfully'
      redirect_to(subjects_path)
    else
      @subject_count = Subject.count + 1
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update(subject_params)
      flash[:notice] = 'Subject updated successfully'
      redirect_to(subject_path(@subject))
    else
      @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(form.object) %>




<div class="field mb-4">
  <%= form.label :name, class: "block text-purple-700 text-sm font-bold mb-2" %>
  <%= form.text_field :name, class: "shadow appearance-none border border-purple-500 rounded w-full py-2 px-3 text-purple-700 leading-tight focus:outline-none focus:shadow-outline focus:border-purple-700" %>
</div>

<div class="field mb-4">
  <%= form.label :position, class: "block text-blue-700 text-sm font-bold mb-2" %>
  <%= form.select :position, 1..@subject_count, class: "shadow appearance-none border border-blue-500 rounded w-full py-2 px-3 text-blue-700 leading-tight focus:outline-none focus:shadow-outline focus:border-blue-700" %>
</div>

<div class="field mb-4">
  <%= form.label :visible, class: "block text-green-700 text-sm font-bold mb-2" %>
  <div class="flex items-center">
    <%= form.check_box :visible, class: "mr-2 leading-tight text-green-700 focus:ring-green-500" %>
    <%= form.label :visible, "Visible", class: "text-green-700 text-sm" %>
  </div>
</div>

<div class="field mb-4">
  <%= form.label :created, class: "block text-purple-700 text-sm font-bold mb-2" %>
  <%= form.datetime_select :created_at, :order => [:month, :day, :year], class: "shadow appearance-none border border-purple-500 rounded w-full py-2 px-3 text-purple-700 leading-tight focus:outline-none focus:shadow-outline focus:border-purple-700" %>
</div>

<div class="actions mt-4">
    <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
  </div>

app/views/subjects/delete.html.erb
<% @page_title = "Delete Subject" %>

<h1 class="text-3xl font-bold text-center text-black mb-6">Delete Subject</h1>

<div class="text-center mb-4">
  <%= link_to("<< back to List", subjects_path, class: "text-blue-500 hover:underline") %>
</div>

<div class="bg-white p-6 rounded-lg shadow-lg mx-auto max-w-lg">
  <h2 class="text-xl font-bold text-red-500 mb-4">Delete Subject</h2>

  <%= form_for(@subject, method: :delete) do |form| %>
    <p class="text-gray-700 mb-4">Are you sure you want to permanently delete this subject?</p>

    <p class="text-lg font-semibold text-gray-900 mb-4"><%= form.object.name %></p>

    <div class="flex justify-center">
      <%= form.submit("Delete Subject", class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded") %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<% @page_title = "Update Subject" %>

<h1 class="text-3xl font-bold text-center text-black mb-6">Edit Subject</h1>

<div class="text-center mb-4">
  <%= link_to("<< back to List", subjects_path, class: "text-blue-500 hover:underline") %>
</div>

<%= form_with(model: @subject, local: true, class: "bg-white p-6 rounded-lg shadow-lg") do |form| %>

  <% if @subject.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
      <strong class="font-bold"><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</strong>
      <span class="block sm:inline">
        <ul>
          <% @subject.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </span>
    </div>
  <% end %>

  <%= render(:partial => 'form', :locals => { form: form }) %>

  <div class="text-center mt-4">
    <%= form.submit "Update Subject", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/subjects/index.html.erb
<% @page_title = "All Subjects" %>

<!-- app/views/subjects/index.html.erb -->
<h1 class="text-3xl font-bold text-center text-black mb-6">All Subjects</h1>

<div class="text-center mb-4 flex flex-row-reverse">
  <%= link_to("Add New Subject", new_subject_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded") %>
</div>

<div class="overflow-x-auto">
  <table class="min-w-full bg-white rounded-lg shadow-lg">
    <thead>
      <tr class="bg-gray-800 text-white">
        <th class="w-1/12 py-2 px-4">#</th>
        <th class="w-3/12 py-2 px-4">Subject</th>
        <th class="w-2/12 py-2 px-4">Visible</th>
        <th class="w-2/12 py-2 px-4">Pages</th>
        <th class="w-4/12 py-2 px-4">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr class="border-b border-gray-200 hover:bg-gray-100">
          <td class="py-2 px-4 text-center"><%= subject.position %></td>
          <td class="py-2 px-4"><%= subject.name %></td>
          <td class="py-2 px-4 text-center">
            <% if subject.visible %>
              <span class="inline-block w-6 h-6 bg-green-500 rounded-full"></span>
            <% else %>
              <span class="inline-block w-6 h-6 bg-red-500 rounded-full"></span>
            <% end %>
          </td>
          <td class="py-2 px-4 text-center"><%= subject.pages.size %></td>
          <td class="py-2 px-4 text-center space-x-2 flex justify-center">
            <%= link_to("Show", subject_path(subject), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded') %>
            <%= link_to("Edit", edit_subject_path(subject), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-2 rounded') %>
            <%= link_to("Delete", delete_subject_path(subject), class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subjects/new.html.erb
<% @page_title = "Add New Subject" %>

<h1 class="text-3xl font-bold text-center text-black mb-6">New Subject</h1>

<div class="text-center mb-4">
  <%= link_to "<< back to List", subjects_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
</div>



<%= form_with(model: @subject, local: true, class: "bg-white p-8 rounded shadow-md max-w-lg mx-auto") do |form| %>
  
  

  <%= render partial: 'form', locals: { form: form } %>

  
<% end %>

app/views/subjects/show.html.erb
<% @page_title = "Show Subject" %>

<h1 class="text-3xl font-bold text-center text-black mb-6">Subject Details</h1>

<div class="text-center mb-4">
  <%= link_to("<< back to List", subjects_path, class: "text-blue-500 hover:underline") %>
</div>

<div class="overflow-x-auto">
  <table class="min-w-full bg-white rounded-lg shadow-lg">
    <thead>
      <tr class="bg-gray-800 text-white">
        <th class="py-2 px-4">#</th>
        <th class="py-2 px-4">Subject</th>
        <th class="py-2 px-4">Visible</th>
        <th class="py-2 px-4">Pages</th>
        <th class="py-2 px-4">Created</th>
        <th class="py-2 px-4">Updated</th>
        <th class="py-2 px-4">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr class="border-b border-gray-200 hover:bg-gray-100">
        <td class="py-2 px-4 text-center"><%= @subject.position %></td>
        <td class="py-2 px-4"><%= @subject.name %></td>
        <td class="py-2 px-4 text-center">
          <% if @subject.visible %>
            <span class="inline-block w-6 h-6 bg-green-500 rounded-full"></span>
          <% else %>
            <span class="inline-block w-6 h-6 bg-red-500 rounded-full"></span>
          <% end %>
        </td>
        <td class="py-2 px-4 text-center"><%= @subject.pages.size %></td>
        <td class="py-2 px-4"><%= @subject.created_at.strftime("%B %d, %Y") %></td>
        <td class="py-2 px-4"><%= @subject.updated_at.strftime("%B %d, %Y") %></td>
        <td class="py-2 px-4 text-center space-x-2 flex justify-center">
          <%= link_to("Show", subject_path(@subject), class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-2 rounded') %>
          <%= link_to("Edit", edit_subject_path(@subject), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-2 rounded') %>
          <%= link_to("Delete", delete_subject_path(@subject), method: :delete, data: { confirm: "Are you sure?" }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded') %>
        </td>
      </tr>
    </tbody>
  </table>
</div>